// Auto-generated: 332 Hay Day food/product items (name, level, building) in the original list order.
export type FoodItem = { id: number; name: string; level: number; building: string };

export const FOOD_PRICE_USDT = 0.001625;

export const FOOD_ITEMS: FoodItem[] = [
  { id: 0, name: "Lamb Doner Wrap", level: 32, building: "Doner Kebab Stand" },
  { id: 1, name: "Spicy Bean Doner", level: 32, building: "Doner Kebab Stand" },
  { id: 2, name: "Tower Doner Supreme", level: 58, building: "Doner Kebab Stand" },
  { id: 3, name: "Fresh Diffuser", level: 110, building: "Perfumerie" },
  { id: 4, name: "Zesty Perfume", level: 113, building: "Perfumerie" },
  { id: 5, name: "Calming Diffuser", level: 116, building: "Perfumerie" },
  { id: 6, name: "Lemon Essential Oil", level: 68, building: "Essential Oils Lab" },
  { id: 7, name: "Mint Essential Oil", level: 85, building: "Essential Oils Lab" },
  { id: 8, name: "Ginger Essential Oil", level: 80, building: "Essential Oils Lab" },
  { id: 9, name: "Chamomile Essential Oil", level: 74, building: "Essential Oils Lab" },
  { id: 10, name: "Vanilla Milkshake", level: 124, building: "Milkshake Bar" },
  { id: 11, name: "Mocha Milkshake", level: 125, building: "Milkshake Bar" },
  { id: 12, name: "Fruity Milkshake", level: 126, building: "Milkshake Bar" },
  { id: 13, name: "Apple Porridge", level: 119, building: "Porridge Bar" },
  { id: 14, name: "Sweet Porridge", level: 120, building: "Porridge Bar" },
  { id: 15, name: "Fresh Porridge", level: 122, building: "Porridge Bar" },
  { id: 16, name: "Colorful Omelet", level: 77, building: "Omelet Station" },
  { id: 17, name: "Spring Omelet", level: 77, building: "Omelet Station" },
  { id: 18, name: "Rice Omelet", level: 83, building: "Omelet Station" },
  { id: 19, name: "Cheese Omelet", level: 79, building: "Omelet Station" },
  { id: 20, name: "Potato Omelet", level: 87, building: "Omelet Station" },
  { id: 21, name: "Plain Waffles", level: 114, building: "Waffle Maker" },
  { id: 22, name: "Breakfast Waffles", level: 119, building: "Waffle Maker" },
  { id: 23, name: "Berry Waffles", level: 114, building: "Waffle Maker" },
  { id: 24, name: "Chocolate Waffles", level: 117, building: "Waffle Maker" },
  { id: 25, name: "Blueberry Waffles", level: 118, building: "Waffle Maker" },
  { id: 26, name: "Plain Cupcake", level: 109, building: "Cupcake Maker" },
  { id: 27, name: "Tropical Cupcake", level: 112, building: "Cupcake Maker" },
  { id: 28, name: "Cookie Cupcake", level: 114, building: "Cupcake Maker" },
  { id: 29, name: "Guava Cupcake", level: 109, building: "Cupcake Maker" },
  { id: 30, name: "Chickpea Stew", level: 106, building: "Stew Pot" },
  { id: 31, name: "Winter Stew", level: 112, building: "Stew Pot" },
  { id: 32, name: "Chili Stew", level: 109, building: "Stew Pot" },
  { id: 33, name: "Plain Yogurt", level: 103, building: "Yogurt Maker" },
  { id: 34, name: "Strawberry Yogurt", level: 105, building: "Yogurt Maker" },
  { id: 35, name: "Tropical Yogurt", level: 109, building: "Yogurt Maker" },
  { id: 36, name: "Breakfast Bowl", level: 119, building: "Yogurt Maker" },
  { id: 37, name: "Mint Fudge", level: 102, building: "Fudge Shop" },
  { id: 38, name: "Chili Fudge", level: 104, building: "Fudge Shop" },
  { id: 39, name: "Lemon Fudge", level: 108, building: "Fudge Shop" },
  { id: 40, name: "Peanut Fudge", level: 111, building: "Fudge Shop" },
  { id: 41, name: "Rich Fudge", level: 99, building: "Fudge Shop" },
  { id: 42, name: "Tea Pot", level: 94, building: "Pottery Studio" },
  { id: 43, name: "Potted Plant", level: 96, building: "Pottery Studio" },
  { id: 44, name: "Clay Mug", level: 99, building: "Pottery Studio" },
  { id: 45, name: "Dried Fruit", level: 102, building: "Preservation Station" },
  { id: 46, name: "Pickles", level: 91, building: "Preservation Station" },
  { id: 47, name: "Canned Fish", level: 95, building: "Preservation Station" },
  { id: 48, name: "Kimchi", level: 98, building: "Preservation Station" },
  { id: 49, name: "Guava Compote", level: 104, building: "Preservation Station" },
  { id: 50, name: "Plain Donut", level: 76, building: "Donut Maker" },
  { id: 51, name: "Cream Donut", level: 86, building: "Donut Maker" },
  { id: 52, name: "Bacon Donut", level: 88, building: "Donut Maker" },
  { id: 53, name: "Filled Donut", level: 93, building: "Donut Maker" },
  { id: 54, name: "Crunchy Donut", level: 82, building: "Donut Maker" },
  { id: 55, name: "Sprinkled Donut", level: 79, building: "Donut Maker" },
  { id: 56, name: "Exfoliating Soap", level: 93, building: "Bath Kiosk" },
  { id: 57, name: "Honey Face Mask", level: 99, building: "Bath Kiosk" },
  { id: 58, name: "Honey Soap", level: 84, building: "Bath Kiosk" },
  { id: 59, name: "Lemon Lotion", level: 84, building: "Bath Kiosk" },
  { id: 60, name: "Rich Soap", level: 121, building: "Bath Kiosk" },
  { id: 61, name: "Peanuts", level: 62, building: "Squirrel Tree" },
  { id: 62, name: "Bacon Fries", level: 87, building: "Deep Fryer" },
  { id: 63, name: "Chili Poppers", level: 98, building: "Deep Fryer" },
  { id: 64, name: "Hand Pies", level: 91, building: "Deep Fryer" },
  { id: 65, name: "Fried Candy Bar", level: 100, building: "Deep Fryer" },
  { id: 66, name: "Falafel", level: 98, building: "Deep Fryer" },
  { id: 67, name: "Samosa", level: 103, building: "Deep Fryer" },
  { id: 68, name: "Caramel Apple", level: 51, building: "Candy Machine" },
  { id: 69, name: "Toffee", level: 52, building: "Candy Machine" },
  { id: 70, name: "Chocolate", level: 54, building: "Candy Machine" },
  { id: 71, name: "Lollipop", level: 57, building: "Candy Machine" },
  { id: 72, name: "Jelly Beans", level: 60, building: "Candy Machine" },
  { id: 73, name: "Sesame Brittle", level: 78, building: "Candy Machine" },
  { id: 74, name: "Honey Peanuts", level: 63, building: "Candy Machine" },
  { id: 75, name: "Cotton Candy", level: 75, building: "Candy Machine" },
  { id: 76, name: "Fish Meat", level: 27, building: "Fish Boat" },
  { id: 77, name: "Lobster Meat", level: 44, building: "Fish Boat" },
  { id: 78, name: "Duck Down", level: 50, building: "Fish Boat" },
  { id: 79, name: "Cream", level: 6, building: "Dairy" },
  { id: 80, name: "Butter", level: 9, building: "Dairy" },
  { id: 81, name: "Cheese", level: 12, building: "Dairy" },
  { id: 82, name: "Goat Cheese", level: 33, building: "Dairy" },
  { id: 83, name: "Fried Rice", level: 69, building: "Wok Kitchen" },
  { id: 84, name: "Tofu Stir Fry", level: 89, building: "Wok Kitchen" },
  { id: 85, name: "Spicy Fish", level: 79, building: "Wok Kitchen" },
  { id: 86, name: "Peanut Noodles", level: 86, building: "Wok Kitchen" },
  { id: 87, name: "Lamb Stir Fry", level: 69, building: "Wok Kitchen" },
  { id: 88, name: "Cheese Fondue", level: 91, building: "Fondue Pot" },
  { id: 89, name: "Bacon Fondue", level: 86, building: "Fondue Pot" },
  { id: 90, name: "Chocolate Fondue", level: 81, building: "Fondue Pot" },
  { id: 91, name: "Tropical Fondue", level: 100, building: "Fondue Pot" },
  { id: 92, name: "Rustic Bouquet", level: 49, building: "Flowershop" },
  { id: 93, name: "Bright Bouquet", level: 65, building: "Flowershop" },
  { id: 94, name: "Soft Bouquet", level: 93, building: "Flowershop" },
  { id: 95, name: "Candy Bouquet", level: 90, building: "Flowershop" },
  { id: 96, name: "Gracious Bouquet", level: 73, building: "Flowershop" },
  { id: 97, name: "Veggie Bouquet", level: 106, building: "Flowershop" },
  { id: 98, name: "Birthday Bouquet", level: 92, building: "Flowershop" },
  { id: 99, name: "Taco", level: 77, building: "Taco Kitchen" },
  { id: 100, name: "Fish Taco", level: 79, building: "Taco Kitchen" },
  { id: 101, name: "Quesadilla", level: 82, building: "Taco Kitchen" },
  { id: 102, name: "Nachos", level: 87, building: "Taco Kitchen" },
  { id: 103, name: "Spicy Bean Taco", level: 77, building: "Taco Kitchen" },
  { id: 104, name: "Green Tea", level: 80, building: "Tea Stand" },
  { id: 105, name: "Milk Tea", level: 81, building: "Tea Stand" },
  { id: 106, name: "Honey Tea", level: 83, building: "Tea Stand" },
  { id: 107, name: "Lemon Tea", level: 86, building: "Tea Stand" },
  { id: 108, name: "Orange Tea", level: 89, building: "Tea Stand" },
  { id: 109, name: "Ice Tea", level: 92, building: "Tea Stand" },
  { id: 110, name: "Mint Tea", level: 97, building: "Tea Stand" },
  { id: 111, name: "Apple Ginger Tea", level: 88, building: "Tea Stand" },
  { id: 112, name: "Pomegranate Tea", level: 107, building: "Tea Stand" },
  { id: 113, name: "Chamomile Tea", level: 100, building: "Tea Stand" },
  { id: 114, name: "Hot Dog", level: 75, building: "Hot Dog Stand" },
  { id: 115, name: "Tofu Dog", level: 76, building: "Hot Dog Stand" },
  { id: 116, name: "Corn Dog", level: 78, building: "Hot Dog Stand" },
  { id: 117, name: "Onion Dog", level: 80, building: "Hot Dog Stand" },
  { id: 118, name: "Gnocchi", level: 72, building: "Pasta Kitchen" },
  { id: 119, name: "Veggie Lasagna", level: 74, building: "Pasta Kitchen" },
  { id: 120, name: "Lobster Pasta", level: 79, building: "Pasta Kitchen" },
  { id: 121, name: "Pasta Carbonara", level: 83, building: "Pasta Kitchen" },
  { id: 122, name: "Spicy Pasta", level: 87, building: "Pasta Kitchen" },
  { id: 123, name: "Broccoli Pasta", level: 83, building: "Pasta Kitchen" },
  { id: 124, name: "Mushroom Pasta", level: 101, building: "Pasta Kitchen" },
  { id: 125, name: "Fresh Pasta", level: 67, building: "Pasta Maker" },
  { id: 126, name: "Rice Noodles", level: 73, building: "Pasta Maker" },
  { id: 127, name: "Cloche Hat", level: 70, building: "Hat Maker" },
  { id: 128, name: "Top Hat", level: 72, building: "Hat Maker" },
  { id: 129, name: "Sun Hat", level: 74, building: "Hat Maker" },
  { id: 130, name: "Flower Crown", level: 86, building: "Hat Maker" },
  { id: 131, name: "Bread", level: 2, building: "Bakery" },
  { id: 132, name: "Cookie", level: 10, building: "Bakery" },
  { id: 133, name: "Corn Bread", level: 7, building: "Bakery" },
  { id: 134, name: "Pizza", level: 33, building: "Bakery" },
  { id: 135, name: "Spicy Pizza", level: 37, building: "Bakery" },
  { id: 136, name: "Raspberry Muffin", level: 19, building: "Bakery" },
  { id: 137, name: "Blackberry Muffin", level: 26, building: "Bakery" },
  { id: 138, name: "Potato Bread", level: 39, building: "Bakery" },
  { id: 139, name: "Frutti di Mare Pizza", level: 45, building: "Bakery" },
  { id: 140, name: "Banana Bread", level: 91, building: "Bakery" },
  { id: 141, name: "Gingerbread Cookie", level: 86, building: "Bakery" },
  { id: 142, name: "Macaroon", level: 101, building: "Bakery" },
  { id: 143, name: "Pineapple Coconut Bars", level: 120, building: "Bakery" },
  { id: 144, name: "Blueberry Muffin", level: 33, building: "Bakery" },
  { id: 145, name: "Brown Sugar", level: 7, building: "Sugar Mill" },
  { id: 146, name: "White Sugar", level: 13, building: "Sugar Mill" },
  { id: 147, name: "Syrup", level: 18, building: "Sugar Mill" },
  { id: 148, name: "Popcorn", level: 8, building: "Popcorn Pot" },
  { id: 149, name: "Butter Popcorn", level: 16, building: "Popcorn Pot" },
  { id: 150, name: "Chili Popcorn", level: 25, building: "Popcorn Pot" },
  { id: 151, name: "Chocolate Popcorn", level: 44, building: "Popcorn Pot" },
  { id: 152, name: "Honey Popcorn", level: 40, building: "Popcorn Pot" },
  { id: 153, name: "Snack Mix", level: 64, building: "Popcorn Pot" },
  { id: 154, name: "Pancakes", level: 9, building: "BBQ Grill" },
  { id: 155, name: "Bacon and Eggs", level: 11, building: "BBQ Grill" },
  { id: 156, name: "Hamburger", level: 18, building: "BBQ Grill" },
  { id: 157, name: "Roasted Tomatoes", level: 30, building: "BBQ Grill" },
  { id: 158, name: "Baked Potato", level: 35, building: "BBQ Grill" },
  { id: 159, name: "Fishburger", level: 27, building: "BBQ Grill" },
  { id: 160, name: "Fish and Chips", level: 41, building: "BBQ Grill" },
  { id: 161, name: "Lobster Skewer", level: 48, building: "BBQ Grill" },
  { id: 162, name: "Grilled Onion", level: 68, building: "BBQ Grill" },
  { id: 163, name: "Banana Pancakes", level: 94, building: "BBQ Grill" },
  { id: 164, name: "Grilled Eggplant", level: 90, building: "BBQ Grill" },
  { id: 165, name: "Fish Skewer", level: 96, building: "BBQ Grill" },
  { id: 166, name: "Winter Veggies", level: 72, building: "BBQ Grill" },
  { id: 167, name: "Garlic Bread", level: 60, building: "BBQ Grill" },
  { id: 168, name: "Stuffed Peppers", level: 80, building: "BBQ Grill" },
  { id: 169, name: "Grilled Asparagus", level: 67, building: "BBQ Grill" },
  { id: 170, name: "Grilled Lamb Skewer", level: 25, building: "BBQ Grill" },
  { id: 171, name: "Carrot Pie", level: 14, building: "Pie Oven" },
  { id: 172, name: "Bacon Pie", level: 18, building: "Pie Oven" },
  { id: 173, name: "Pumpkin Pie", level: 15, building: "Pie Oven" },
  { id: 174, name: "Apple Pie", level: 28, building: "Pie Oven" },
  { id: 175, name: "Feta Pie", level: 34, building: "Pie Oven" },
  { id: 176, name: "Casserole", level: 36, building: "Pie Oven" },
  { id: 177, name: "Shepherds Pie", level: 39, building: "Pie Oven" },
  { id: 178, name: "Fish Pie", level: 28, building: "Pie Oven" },
  { id: 179, name: "Lemon Pie", level: 67, building: "Pie Oven" },
  { id: 180, name: "Peach Tart", level: 76, building: "Pie Oven" },
  { id: 181, name: "Eggplant Parmesan", level: 99, building: "Pie Oven" },
  { id: 182, name: "Chocolate Pie", level: 65, building: "Pie Oven" },
  { id: 183, name: "Mushroom Pot Pie", level: 97, building: "Pie Oven" },
  { id: 184, name: "Passion Fruit Pie", level: 92, building: "Pie Oven" },
  { id: 185, name: "Asparagus Quiche", level: 49, building: "Pie Oven" },
  { id: 186, name: "Sweater", level: 17, building: "Loom" },
  { id: 187, name: "Blue Woolly Hat", level: 19, building: "Loom" },
  { id: 188, name: "Blue Sweater", level: 20, building: "Loom" },
  { id: 189, name: "Red Scarf", level: 48, building: "Loom" },
  { id: 190, name: "Cotton Fabrics", level: 18, building: "Loom" },
  { id: 191, name: "Flower Shawl", level: 71, building: "Loom" },
  { id: 192, name: "Cheese Cake", level: 24, building: "Cake Oven" },
  { id: 193, name: "Carrot Cake", level: 21, building: "Cake Oven" },
  { id: 194, name: "Birthday Cake", level: 23, building: "Cake Oven" },
  { id: 195, name: "Chocolate Cake", level: 36, building: "Cake Oven" },
  { id: 196, name: "Strawberry Cake", level: 35, building: "Cake Oven" },
  { id: 197, name: "Berry Cake", level: 23, building: "Cake Oven" },
  { id: 198, name: "Potato Feta Cake", level: 38, building: "Cake Oven" },
  { id: 199, name: "Lemon Cake", level: 68, building: "Cake Oven" },
  { id: 200, name: "Honey Apple Cake", level: 42, building: "Cake Oven" },
  { id: 201, name: "Fruit Cake", level: 89, building: "Cake Oven" },
  { id: 202, name: "Pineapple Cake", level: 65, building: "Cake Oven" },
  { id: 203, name: "Fancy Cake", level: 54, building: "Cake Oven" },
  { id: 204, name: "Chocolate Roll", level: 95, building: "Cake Oven" },
  { id: 205, name: "Pomegranate Cake", level: 108, building: "Cake Oven" },
  { id: 206, name: "Blueberry Cheesecake", level: 31, building: "Cake Oven" },
  { id: 207, name: "Silver Bar", level: 24, building: "Smelter" },
  { id: 208, name: "Gold Bar", level: 25, building: "Smelter" },
  { id: 209, name: "Platinum Bar", level: 25, building: "Smelter" },
  { id: 210, name: "Coal Bar", level: 33, building: "Smelter" },
  { id: 211, name: "Iron Bar", level: 34, building: "Smelter" },
  { id: 212, name: "Carrot Juice", level: 26, building: "Juice Press" },
  { id: 213, name: "Tomato Juice", level: 31, building: "Juice Press" },
  { id: 214, name: "Apple Juice", level: 28, building: "Juice Press" },
  { id: 215, name: "Cherry Juice", level: 30, building: "Juice Press" },
  { id: 216, name: "Berry Juice", level: 31, building: "Juice Press" },
  { id: 217, name: "Orange Juice", level: 71, building: "Juice Press" },
  { id: 218, name: "Grape Juice", level: 84, building: "Juice Press" },
  { id: 219, name: "Watermelon Juice", level: 92, building: "Juice Press" },
  { id: 220, name: "Pineapple Juice", level: 52, building: "Juice Press" },
  { id: 221, name: "Passion Fruit Juice", level: 88, building: "Juice Press" },
  { id: 222, name: "Mango Juice", level: 97, building: "Juice Press" },
  { id: 223, name: "Guava Juice", level: 104, building: "Juice Press" },
  { id: 224, name: "Vanilla Ice Cream", level: 29, building: "Ice Cream Maker" },
  { id: 225, name: "Cherry Popsicle", level: 33, building: "Ice Cream Maker" },
  { id: 226, name: "Strawberry Ice Cream", level: 34, building: "Ice Cream Maker" },
  { id: 227, name: "Chocolate Ice Cream", level: 39, building: "Ice Cream Maker" },
  { id: 228, name: "Orange Sorbet", level: 78, building: "Ice Cream Maker" },
  { id: 229, name: "Peach Ice Cream", level: 83, building: "Ice Cream Maker" },
  { id: 230, name: "Banana Split", level: 96, building: "Ice Cream Maker" },
  { id: 231, name: "Mint Ice Cream", level: 85, building: "Ice Cream Maker" },
  { id: 232, name: "Sesame Ice Cream", level: 50, building: "Ice Cream Maker" },
  { id: 233, name: "Peanut Butter Milkshake", level: 68, building: "Ice Cream Maker" },
  { id: 234, name: "Affogato", level: 76, building: "Ice Cream Maker" },
  { id: 235, name: "Coconut Ice Cream", level: 102, building: "Ice Cream Maker" },
  { id: 236, name: "Fruit Sorbet", level: 106, building: "Ice Cream Maker" },
  { id: 237, name: "Apple Jam", level: 35, building: "Jam Maker" },
  { id: 238, name: "Raspberry Jam", level: 36, building: "Jam Maker" },
  { id: 239, name: "Blackberry Jam", level: 37, building: "Jam Maker" },
  { id: 240, name: "Cherry Jam", level: 38, building: "Jam Maker" },
  { id: 241, name: "Strawberry Jam", level: 50, building: "Jam Maker" },
  { id: 242, name: "Marmelade", level: 74, building: "Jam Maker" },
  { id: 243, name: "Peach Jam", level: 79, building: "Jam Maker" },
  { id: 244, name: "Grape Jam", level: 85, building: "Jam Maker" },
  { id: 245, name: "Plum Jam", level: 94, building: "Jam Maker" },
  { id: 246, name: "Passion Fruit Jam", level: 96, building: "Jam Maker" },
  { id: 247, name: "Blueberry Chutney", level: 70, building: "Jam Maker" },
  { id: 248, name: "Bracelet", level: 38, building: "Jeweler" },
  { id: 249, name: "Necklace", level: 39, building: "Jeweler" },
  { id: 250, name: "Diamond Ring", level: 40, building: "Jeweler" },
  { id: 251, name: "Iron Bracelet", level: 41, building: "Jeweler" },
  { id: 252, name: "Flower Pendant", level: 98, building: "Jeweler" },
  { id: 253, name: "Espreso", level: 42, building: "Coffee Kiosk" },
  { id: 254, name: "Latte", level: 43, building: "Coffee Kiosk" },
  { id: 255, name: "Mocha", level: 45, building: "Coffee Kiosk" },
  { id: 256, name: "Raspberry Mocha", level: 46, building: "Coffee Kiosk" },
  { id: 257, name: "Hot Chocolate", level: 47, building: "Coffee Kiosk" },
  { id: 258, name: "Iced Banana Latte", level: 88, building: "Coffee Kiosk" },
  { id: 259, name: "Caramel Latte", level: 62, building: "Coffee Kiosk" },
  { id: 260, name: "Lobster Soup", level: 46, building: "Soup Kitchen" },
  { id: 261, name: "Tomato Soup", level: 47, building: "Soup Kitchen" },
  { id: 262, name: "Fish Soup", level: 53, building: "Soup Kitchen" },
  { id: 263, name: "Pumpkin Soup", level: 49, building: "Soup Kitchen" },
  { id: 264, name: "Noodle Soup", level: 73, building: "Soup Kitchen" },
  { id: 265, name: "Onion Soup", level: 72, building: "Soup Kitchen" },
  { id: 266, name: "Potato Soup", level: 78, building: "Soup Kitchen" },
  { id: 267, name: "Bell Pepper Soup", level: 81, building: "Soup Kitchen" },
  { id: 268, name: "Broccoli Soup", level: 87, building: "Soup Kitchen" },
  { id: 269, name: "Mushroom Soup", level: 104, building: "Soup Kitchen" },
  { id: 270, name: "Cabbage Soup", level: 65, building: "Soup Kitchen" },
  { id: 271, name: "Asparagus Soup", level: 51, building: "Soup Kitchen" },
  { id: 272, name: "Lamb Soup", level: 46, building: "Soup Kitchen" },
  { id: 273, name: "Soy Sauce", level: 54, building: "Sauce Maker" },
  { id: 274, name: "Olive Oil", level: 60, building: "Sauce Maker" },
  { id: 275, name: "Mayonaise", level: 62, building: "Sauce Maker" },
  { id: 276, name: "Lemon Curd", level: 66, building: "Sauce Maker" },
  { id: 277, name: "Tomato Sauce", level: 69, building: "Sauce Maker" },
  { id: 278, name: "Salsa", level: 77, building: "Sauce Maker" },
  { id: 279, name: "Olive Dip", level: 62, building: "Sauce Maker" },
  { id: 280, name: "Tart Dressing", level: 100, building: "Sauce Maker" },
  { id: 281, name: "Hummus", level: 95, building: "Sauce Maker" },
  { id: 282, name: "Bean Dip", level: 54, building: "Sauce Maker" },
  { id: 283, name: "SushiRoll", level: 56, building: "Sushi Bar" },
  { id: 284, name: "LobsterSushi", level: 59, building: "Sushi Bar" },
  { id: 285, name: "EggRoll", level: 63, building: "Sushi Bar" },
  { id: 286, name: "Big Sushi Roll", level: 76, building: "Sushi Bar" },
  { id: 287, name: "Rice Ball", level: 110, building: "Sushi Bar" },
  { id: 288, name: "Greek Salad", level: 58, building: "Salad Bar" },
  { id: 289, name: "Bacon Salad", level: 62, building: "Salad Bar" },
  { id: 290, name: "Seafood Salad", level: 64, building: "Salad Bar" },
  { id: 291, name: "Pasta Salad", level: 67, building: "Salad Bar" },
  { id: 292, name: "Fruit Salad", level: 82, building: "Salad Bar" },
  { id: 293, name: "Summer Salad", level: 84, building: "Salad Bar" },
  { id: 294, name: "Summer Rolls", level: 78, building: "Salad Bar" },
  { id: 295, name: "Veggie Platter", level: 74, building: "Salad Bar" },
  { id: 296, name: "Mushroom Salad", level: 89, building: "Salad Bar" },
  { id: 297, name: "Beetroot Salad", level: 76, building: "Salad Bar" },
  { id: 298, name: "Coleslaw", level: 75, building: "Salad Bar" },
  { id: 299, name: "Orange Salad", level: 117, building: "Salad Bar" },
  { id: 300, name: "Bean Salad", level: 58, building: "Salad Bar" },
  { id: 301, name: "Bacon Toast", level: 65, building: "Sandwich Bar" },
  { id: 302, name: "Veggie Bagel", level: 61, building: "Sandwich Bar" },
  { id: 303, name: "Egg Sandwich", level: 66, building: "Sandwich Bar" },
  { id: 304, name: "Honey Toast", level: 69, building: "Sandwich Bar" },
  { id: 305, name: "Goat Cheese Toast", level: 92, building: "Sandwich Bar" },
  { id: 306, name: "Onion Melt", level: 84, building: "Sandwich Bar" },
  { id: 307, name: "Cucumber Sandwich", level: 79, building: "Sandwich Bar" },
  { id: 308, name: "Peanut Butter Sandwich", level: 71, building: "Sandwich Bar" },
  { id: 309, name: "Hummus Wrap", level: 109, building: "Sandwich Bar" },
  { id: 310, name: "Green Smoothie", level: 66, building: "Smoothie Mixer" },
  { id: 311, name: "Berry Smoothie", level: 64, building: "Smoothie Mixer" },
  { id: 312, name: "Yogurt Smoothie", level: 70, building: "Smoothie Mixer" },
  { id: 313, name: "Mixed Smoothie", level: 88, building: "Smoothie Mixer" },
  { id: 314, name: "Cocoa Smoothie", level: 100, building: "Smoothie Mixer" },
  { id: 315, name: "Plum Smoothie", level: 102, building: "Smoothie Mixer" },
  { id: 316, name: "Cucumber Smoothie", level: 70, building: "Smoothie Mixer" },
  { id: 317, name: "Sesame Smoothie", level: 93, building: "Smoothie Mixer" },
  { id: 318, name: "Tropical Smoothie", level: 104, building: "Smoothie Mixer" },
  { id: 319, name: "Cotton Shirt", level: 19, building: "Sewing Machine" },
  { id: 320, name: "Wooly Pants", level: 21, building: "Sewing Machine" },
  { id: 321, name: "Violet Dress", level: 25, building: "Sewing Machine" },
  { id: 322, name: "Pillow", level: 51, building: "Sewing Machine" },
  { id: 323, name: "Blanket", level: 59, building: "Sewing Machine" },
  { id: 324, name: "Soothing Pad", level: 45, building: "Sewing Machine" },
  { id: 325, name: "Honey", level: 39, building: "Honey Extractor" },
  { id: 326, name: "Beeswax", level: 48, building: "Honey Extractor" },
  { id: 327, name: "Strawberry Candle", level: 48, building: "Candle Maker" },
  { id: 328, name: "Raspberry Candle", level: 52, building: "Candle Maker" },
  { id: 329, name: "Lemon Candle", level: 72, building: "Candle Maker" },
  { id: 330, name: "Floral Candle", level: 95, building: "Candle Maker" },
  { id: 331, name: "Colorful Candle", level: 84, building: "Candle Maker" },
];
