// English labels for the admin panel (Arabic text is the key). Unknown strings fall back to Arabic.
export const EN: Record<string, string> = {
 "آخر دخول": "Last login",
 "أدنى مبلغ": "Min amount",
 "أسعار الصرف": "Exchange rates",
 "أسعار العملات": "Currency rates",
 "أسعار المنتجات كلها بالـ USDT. عند الشراء أو الشحن بعملة أخرى يُحوَّل المبلغ بهذه الأسعار. كل طلب شحن يثبّت السعر وقت إنشائه فلا يتغير إن عدّلت السعر لاحقًا. القيم الافتراضية أولية — راجعها.": "All product prices are in USDT. Purchases and top-ups in other currencies are converted with these rates. Each top-up locks the rate when created, so later changes don't affect it. Default values are placeholders — review them.",
 "أضف قسمًا أولًا.": "Add a category first.",
 "أعلى مبلغ (0 = بلا حد)": "Max amount (0 = no limit)",
 "أقسام المتجر والأدوات": "Store categories & tools",
 "أكواد الاشتراك وطلباتها": "Subscription codes & orders",
 "إجمالي": "Total",
 "إرسال إشعار لكل المستخدمين": "Send a notification to all users",
 "إرسال إشعار مرة أخرى": "Send notification again",
 "إرسال الرد": "Send reply",
 "إزالة كل الأسعار الخاصة": "Remove all special prices",
 "إزالة كل الأسعار الخاصة؟": "Remove all special prices?",
 "إضافة": "Add",
 "إضافة أكواد (كود في كل سطر)": "Add codes (one per line)",
 "إضافة الأكواد": "Add codes",
 "إضافة باقة اشتراك": "Add subscription plan",
 "إضافة صندوق": "Add box",
 "إضافة طريقة دفع": "Add payment method",
 "إضافة قسم": "Add category",
 "إضافة مجموعة": "Add group",
 "إضافة مزرعة": "Add farm",
 "إضافة منتج": "Add product",
 "إظهار شريط إعلاني في أعلى التطبيق": "Show a banner at the top of the app",
 "إعلان جديد": "New announcement",
 "إلغاء": "Cancel",
 "إلغاء الطلب وإرجاع المبلغ للمستخدم؟": "Cancel the order and refund the user?",
 "إلغاء الطلب؟": "Cancel the order?",
 "إلغاء وإرجاع": "Cancel & refund",
 "إلى": "To",
 "اسم الباقة": "Plan name",
 "اسم الصندوق": "Box name",
 "اسم الطريقة": "Method name",
 "اسم العنصر": "Item name",
 "اسم القسم": "Category name",
 "اسم المجموعة": "Group name",
 "اسم المدير": "Admin username",
 "اسم المزرعة": "Farm name",
 "اعتماد بالمبلغ المدفوع": "Approve with paid amount",
 "اعتماد بالمبلغ المطلوب": "Approve with requested amount",
 "اعتماد وإضافة": "Approve & credit",
 "اعتماد وإضافة الرصيد": "Approve & credit balance",
 "اكتب ردك": "Write your reply",
 "الأقسام": "Categories",
 "الأكواد المتاحة": "Available codes",
 "الإجراء": "Action",
 "الإعدادات والصيانة": "Settings & maintenance",
 "الإعلانات": "Announcements",
 "الإيداعات (السابقة)": "Deposits (previous)",
 "البيانات مكتملة": "Data complete",
 "التاريخ": "Date",
 "الترتيب": "Order",
 "التسجيلات آخر 14 يومًا": "Sign-ups, last 14 days",
 "الجوائز": "Prizes",
 "الحد الأقصى للطلب الواحد (0 = بلا حد)": "Max per order (0 = no limit)",
 "الرئيسية": "Dashboard",
 "الرصيد قبل": "Balance before",
 "السبب": "Reason",
 "السبب (مطلوب)": "Reason (required)",
 "السجل المالي (للقراءة فقط · لا يمكن حذفه)": "Financial ledger (read-only · cannot be deleted)",
 "السعر (USDT)": "Price (USDT)",
 "السعر الافتراضي للقطعة الواحدة": "Default price per item",
 "الطريقة": "Method",
 "العدد (قطع في العبوة)": "Pack size (pieces)",
 "العملة": "Currency",
 "العنوان": "Title",
 "الفرق": "Difference",
 "القسم": "Category",
 "الكمية المتوفرة (-1 = غير محدودة)": "Stock (-1 = unlimited)",
 "الكيان": "Entity",
 "المبلغ": "Amount",
 "المبلغ (موجب للإضافة، سالب للخصم)": "Amount (positive to add, negative to deduct)",
 "المبلغ المدفوع فعليًا": "Actually paid amount",
 "المجموعات": "Groups",
 "المخزون": "Stock",
 "المدفوع": "Paid",
 "المرجع": "Reference",
 "المزارع": "Farms",
 "المسؤول": "Admin",
 "المستخدم": "User",
 "المستخدمون": "Users",
 "المستخدمون والأرصدة": "Users & balances",
 "المستوى": "Level",
 "المطلوب": "Requested",
 "المنتجات": "Products",
 "المنتجات العشوائية": "Random boxes",
 "المنفّذ": "Actor",
 "النص": "Text",
 "النوع": "Type",
 "الوزن": "Weight",
 "الوصف": "Description",
 "بحث": "Search",
 "بعد": "After",
 "بلا بيانات": "No data",
 "بيانات الدخول غير صحيحة.": "Invalid credentials.",
 "بيانات المزارع (ID / Token)": "Farm data (ID / Token)",
 "تأكيد تعديل الرصيد؟": "Confirm balance adjustment?",
 "تثبيت في الأعلى": "Pin to top",
 "تحديث إجباري": "Force update",
 "تحديث ملف التطبيق (APK) نادر جدًا الآن: كل تعديلات التصميم والمحتوى تظهر مباشرة. استخدم هذا فقط لو غُيّر الغلاف الأصلي للتطبيق.": "APK updates are now very rare: all design and content changes appear live. Use this only if the native app shell itself changed.",
 "تسجيل": "Sign-ups",
 "تسليم": "Deliver",
 "تعديل الرصيد": "Adjust balance",
 "تعذّر عرض الصفحة. حاول مرة أخرى.": "Could not display the page. Try again.",
 "تعليمات الدفع": "Payment instructions",
 "تفاصيل": "Details",
 "تفاصيل الطلب": "Order details",
 "تفعيل وضع الصيانة (يُمنع المستخدمون من استخدام التطبيق ويرون الرسالة أدناه)": "Enable maintenance mode (users are blocked and see the message below)",
 "تنفيذ": "Execute",
 "جائزة جديدة": "New prize",
 "حذف": "Delete",
 "حذف الإعلان؟": "Delete the announcement?",
 "حذف الباقة": "Delete plan",
 "حذف الباقة؟": "Delete the plan?",
 "حذف الجائزة": "Delete prize",
 "حذف الصندوق": "Delete box",
 "حذف الصندوق؟": "Delete the box?",
 "حذف الطريقة؟ إن كانت مرتبطة بعمليات مالية فسيتم تعطيلها فقط.": "Delete the method? If it has financial records it will only be disabled.",
 "حذف القسم": "Delete category",
 "حذف القسم وكل منتجاته؟": "Delete the category and all its products?",
 "حذف المجموعة؟": "Delete the group?",
 "حذف المزرعة؟": "Delete the farm?",
 "حذف المنتج؟": "Delete the product?",
 "حفظ": "Save",
 "حفظ الأسعار": "Save prices",
 "خطأ": "Error",
 "دخول": "Sign in",
 "دعم العملاء": "Customer support",
 "رابط الانضمام (https://...)": "Join link (https://...)",
 "رابط ملف APK": "APK file link",
 "رسائل دعم جديدة": "New support messages",
 "رسالة الصيانة": "Maintenance message",
 "رفض": "Reject",
 "رقم الإصدار الجديد": "New version number",
 "روابط مجموعات المجتمع (واتساب، تيليجرام، ديسكورد...) تظهر للمستخدمين في التطبيق.": "Community group links (WhatsApp, Telegram, Discord…) shown to users in the app.",
 "سبب الرفض (مطلوب)": "Rejection reason (required)",
 "سبب العكس (مطلوب)": "Reversal reason (required)",
 "سجل الإجراءات": "Audit log",
 "سجل الإجراءات (للقراءة فقط · لا يمكن حذفه)": "Audit log (read-only · cannot be deleted)",
 "سجل المحفظة الآمن": "Secure wallet ledger",
 "سجل تعديل الأسعار": "Price change log",
 "سجل تغيّر الحالة": "Status history",
 "سجّلوا اليوم": "Signed up today",
 "سعر الصرف المثبّت": "Locked exchange rate",
 "سعر خاص": "Special price",
 "صندوق عشوائي: يدفع المستخدم سعره فيحصل على إحدى الجوائز عشوائيًا حسب «الوزن». الوزن الأكبر = فرصة أكبر. المخزون -1 = غير محدود.": "Random box: the user pays its price and gets one prize at random by “weight”. Higher weight = higher chance. Stock -1 = unlimited.",
 "طرق الدفع": "Payment methods",
 "طلبات الأكواد": "Code orders",
 "طلبات الشحن": "Top-up requests",
 "طلبات الصناديق العشوائية": "Random box orders",
 "طلبات شحن تنتظر": "Top-up requests waiting",
 "ظاهر": "Visible",
 "ظاهر للمستخدمين": "Visible to users",
 "ظاهرة": "Visible",
 "ظاهرة للمستخدمين": "Visible to users",
 "عكس العملية": "Reverse",
 "عكس العملية وخصم المبلغ من رصيد المستخدم؟": "Reverse the operation and deduct the amount from the user's balance?",
 "قبل": "Before",
 "قطعة": "pcs",
 "قيد التحقق": "Verifying",
 "قيد المراجعة": "Under review",
 "كل باقة لها مخزون أكواد. عند الشراء يُسحب كود متاح تلقائيًا ويُسلَّم للمشتري فورًا.": "Each plan has a code stock. On purchase an available code is taken automatically and delivered instantly.",
 "كلمة المرور": "Password",
 "لا توجد إيداعات.": "No deposits.",
 "لا توجد تعديلات بعد.": "No changes yet.",
 "لا توجد رسائل بعد.": "No messages yet.",
 "لا توجد طلبات.": "No orders.",
 "لا توجد مزارع. أضفها من صفحة «المزارع».": "No farms. Add them from the “Farms” page.",
 "لا يوجد مستخدمون.": "No users.",
 "لوحة الإدارة": "Admin panel",
 "ما الجديد في التحديث (اختياري)": "What's new in the update (optional)",
 "مباع": "Sold",
 "مباعة": "Sold",
 "مبلغ غير مطابق": "Amount mismatch",
 "متاح": "Available",
 "متاحة": "Available",
 "مثبّت": "Pinned",
 "محاولات كثيرة. انتظر دقيقة.": "Too many attempts. Wait a minute.",
 "محظور": "Banned",
 "مخفي": "Hidden",
 "مدة الصلاحية (دقيقة)": "Validity (minutes)",
 "مستوى": "Level",
 "معلومات الدفع (رقم / عنوان المحفظة)": "Payment info (number / wallet address)",
 "مفعّلة": "Active",
 "مقفل مؤقتًا": "Temporarily locked",
 "ملاحظة للمشتري (اختياري)": "Note to buyer (optional)",
 "من": "From",
 "منتجات اختياري – الأسعار": "Optional products – prices",
 "نشر": "Publish",
 "نشط": "Active",
 "نص الإعلان": "Announcement text",
 "هذه البيانات سرية: تُرسل للمشتري فقط عند الضغط على «تسليم» في صفحة تسليم المزارع.": "This data is confidential: it is sent to the buyer only when you press “Deliver” on the farm delivery page.",
 "وصف المزرعة (المستوى، المباني، الخ)": "Farm description (level, buildings, etc.)",
 "وضع الصيانة والشريط الإعلاني": "Maintenance mode & banner",
 "ينتهي": "Expires",
 "يُطبَّق على كل المنتجات التي ليس لها سعر خاص.": "Applies to all products without a special price.",
 "طلبات المزارع": "Farm orders",
 "تسليم المزارع": "Farm delivery",
 "طلبات الأدوات والمنتجات": "Tools & product orders",
 "طلبات منتجات اختياري": "Optional product orders",
 "المدفوعات والمحفظة": "Payments & wallet",
 "المتجر والمنتجات": "Store & products",
 "العملاء والتواصل": "Customers & communication",
 "النظام": "System",
 "طلبات بانتظار التسليم": "Orders awaiting delivery",
 "المزارع المباعة": "Farms sold",
 "المبيعات المكتملة (USDT)": "Completed sales (USDT)",
 "جديد": "New",
 "قيد التنفيذ": "In progress",
 "مكتمل": "Done",
 "ملغي": "Cancelled",
 "تنتظر": "Waiting",
 "الكل": "All",
 "بانتظار الدفع": "Awaiting payment",
 "تم إرسال إثبات الدفع": "Payment proof sent",
 "تمت الموافقة": "Approved",
 "تمت إضافة الرصيد": "Credited",
 "مرفوض": "Rejected",
 "منتهي الصلاحية": "Expired",
 "تم عكس العملية": "Reversed",
 "تعطيل": "Disable",
 "تفعيل": "Enable",
 "تعديل": "Edit",
 "بدء التنفيذ": "Start processing",
 "إلغاء التثبيت": "Unpin",
 "تسجيل الخروج": "Sign out",
 "اللغة": "Language",
 "اسم المستخدم": "Username",
 "بيانات المزرعة": "Farm data",
 "الاسم": "Name",
 "السعر": "Price",
 "الحالة": "Status"
};
